#!/bin/bash
set -e

# TODO: as soon as drivers get added
case "$1" in
    clean)
        make -C kernel clean
        ;;
    kernel)
        make -C kernel -j$(nproc)
        ;;
    *)
        make -C kernel -j$(nproc)
        ;;
esac
